# 4. Grouping and Sorting

In [1]:
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
# sample df
columns = list(load_iris().feature_names)
columns = list(map(lambda x: x[:-5].replace(' ', '_'), columns))

df = pd.DataFrame(columns = columns, data = load_iris().data)
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4
6           4.6          3.4           1.4          0.3
7           5.0          3.4           1.5          0.2
8           4.4          2.9           1.4          0.2
9           4.9          3.1           1.5          0.1

## groupby
- 'DataFrameGroupBy object'를 반환한다.
- 칼럼(들)을 인자로 넣는다. 그러면 칼럼(들)의 unique values을 기준으로 그룹핑이 된다.

In [19]:
# petal width 각각의 값이 몇 개가 존재하는가?
# 방법1
df.groupby('petal_width').petal_width.size()

petal_width
0.1     5
0.2    29
0.3     7
0.4     7
0.5     1
0.6     1
1.0     7
1.1     3
1.2     5
1.3    13
1.4     8
1.5    12
1.6     4
1.7     2
1.8    12
1.9     5
2.0     6
2.1     6
2.2     3
2.3     8
2.4     3
2.5     3
Name: petal_width, dtype: int64

In [3]:
# petal width 각각의 값이 몇 개가 존재하는가?
# 방법2
df.groupby('petal_width').petal_width.count()

petal_width
0.1     5
0.2    29
0.3     7
0.4     7
0.5     1
0.6     1
1.0     7
1.1     3
1.2     5
1.3    13
1.4     8
1.5    12
1.6     4
1.7     2
1.8    12
1.9     5
2.0     6
2.1     6
2.2     3
2.3     8
2.4     3
2.5     3
Name: petal_width, dtype: int64

In [4]:
# petal_width별 sepal_width의 최대값은 무엇인가?
df.groupby('petal_width').sepal_width.max()

petal_width
0.1    4.1
0.2    4.2
0.3    3.8
0.4    4.4
0.5    3.3
0.6    3.5
1.0    2.7
1.1    2.5
1.2    3.0
1.3    3.0
1.4    3.2
1.5    3.2
1.6    3.4
1.7    3.0
1.8    3.2
1.9    2.8
2.0    3.8
2.1    3.3
2.2    3.8
2.3    3.4
2.4    3.4
2.5    3.6
Name: sepal_width, dtype: float64

In [7]:
# petal_width별 sepal_length의 최소값과 최대값은 무엇인가?
df.groupby('petal_width').sepal_length.agg([min, max])

             min  max
petal_width
0.1          4.3  5.2
0.2          4.4  5.8
0.3          4.5  5.7
0.4          5.0  5.7
0.5          5.1  5.1
0.6          5.0  5.0
1.0          4.9  6.0
1.1          5.1  5.6
1.2          5.5  6.1
1.3          5.5  6.6
1.4          5.2  7.0
1.5          5.4  6.9
1.6          6.0  7.2
1.7          4.9  6.7
1.8          5.9  7.3
1.9          5.8  7.4
2.0          5.6  7.9
2.1          6.4  7.6
2.2          6.4  7.7
2.3          6.2  7.7
2.4          5.8  6.7
2.5          6.3  7.2

In [8]:
# 위에서 생성한 데이터프레임을 min -> max 칼럼 순으로 내림차순 정렬한다면?
temp = df.groupby('petal_width').sepal_length.agg([min, max])
temp.sort_values(by = ['min', 'max'], ascending=False)

             min  max
petal_width
2.2          6.4  7.7
2.1          6.4  7.6
2.5          6.3  7.2
2.3          6.2  7.7
1.6          6.0  7.2
1.8          5.9  7.3
1.9          5.8  7.4
2.4          5.8  6.7
2.0          5.6  7.9
1.3          5.5  6.6
1.2          5.5  6.1
1.5          5.4  6.9
1.4          5.2  7.0
1.1          5.1  5.6
0.5          5.1  5.1
0.4          5.0  5.7
0.6          5.0  5.0
1.7          4.9  6.7
1.0          4.9  6.0
0.3          4.5  5.7
0.2          4.4  5.8
0.1          4.3  5.2

In [23]:
# 인덱스를 기준으로 내림차순 정렬하기
df = df.sort_values('sepal_length')     # sepal_length를 기준으로 내림차순 정렬
df = df.sort_index()
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]